### ISSUE TITLE
'}' character in the rocket overview section

### ISSUE THREAD

**Issue by ghost** [PatrykWojcieszak/X-Info#18]
Reproduction:
Go to https://x-info.eu/
Click on Vehicles in top right corner
Click on any available rocket
In Overview section fields LEO, GTO and MARS have a '}' sign after imperial value

Example (Falcon 9):
![specialcharacter](https://user-images.githubusercontent.com/48765880/105180331-b9451b00-5b2a-11eb-92a4-b74fdb33847c.PNG)

**Comment by PatrykWojcieszak** [comment]
Thank you. I already fixed this problem. I will update the website somewhere on the weekend. :)
